name: base
channels:
- conda-forge
dependencies:
# - cffi=1.15.1=py39h1929af6_0
- cudatoolkit=11.5.1
- graphviz=6.0.1
- libgcc-ng=12.1.0
- numpy=1.23.3
- pillow=9.1.1
- pip=22.1.2
- python=3.9.13
# - python_abi=3.9=2_pypy39_pp73
- python-graphviz=0.20.1
- pytorch::pytorch=1.11.0=py3.9_cuda11.5_cudnn8.3.2_0
- pytorch::torchvision=0.12.0=py39_cu115
- requests=2.28.1
- scipy=1.8.1
- ffmpeg=5.0.1
- tqdm=4.64.0
