name: base
channels:
- conda-forge
dependencies:
- ca-certificates=2022.9.24
- certifi=2022.9.24
- cudatoolkit=11.6.0
- graphviz=6.0.1
- libgcc-ng=12.1.0
- numpy=1.23.3
- openssl=1.1.1q
- pillow=9.1.1
- pip=22.1.2
- python=3.9.13
- python-graphviz=0.20.1
- requests=2.28.1
- scipy=1.8.1
- ffmpeg=5.0.1
- tqdm=4.64.0
